name: CIS194
version: '0.1.0.0'
category: Web
author: Anup Kishore
maintainer: anup.kishore@gmail.com
copyright: 2017 Anup Kishore
license: BSD3
github: anup-2s/CIS194
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  - HW1.HW1
  dependencies:
  - base >=4.7 && <5
tests:
  CIS194-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - CIS194
    - hspec
